### ISSUE TITLE
Colour rendering.

### ISSUE THREAD

**Issue by seva1232** [shawn615/MixNeRF#2]
Hello! Thank you for the awesome work!

I'm having some questions about the rendering, correct me, please, if I've misunderstood something. The two MLP net produce the colours, and the final colour of the pixel is computed as a weighted sum of the colours. the MLPs produce Mu and Beta for each point as well, and it it used for the NLL loss, right?

P.S. Do you have any plans on open-sourcing the FlipNeRF code?=)

**Comment by shawn615** [comment]
Thank you for your interest in our MixNeRF. :)

First of all, we perform coarse sampling and fine sampling with **a single MLP** as same as mip-NeRF.
And **the estimated mu is exactly the same as the estimated color.**
In other words, we use the notation mu for the estimated colors in our MixNeRF because we leverage the mixture modeling framework and we use the estimated colors as the location parameter mu for our mixture model.
However, it's just the difference in the notation, the mu and color are not the different outputs, they are the same.

Regarding the FlipNeRF code, yes we will but we are polishing our code yet, so please stay tuned for our FlipNeRF. :)
And thank you for your interest in our works again. :)

**Comment by seva1232** [comment]
Thank you for your answer! 

Looking forward for the FlipNeRF=) May I ask some questions about it here? Did you try to render the colour and use MSE part for the flipped rays? Or there is some reason to avoid doing so?

Thank you once more for the quick answer!

**Comment by shawn615** [comment]
> Thank you for your answer!
> 
> Looking forward for the FlipNeRF=) May I ask some questions about it here? Did you try to render the colour and use MSE part for the flipped rays? Or there is some reason to avoid doing so?
> 
> Thank you once more for the quick answer!

Sorry for the late reply. :(

We use the MSE Loss only for the original input rays because we conjecture that the quality of rendered pixel values can be degraded if we use the MSE Loss on both of the original input rays and flipped reflection rays, which are not the GT rays but newly generated auxiliary rays.
