### ISSUE TITLE
Unexpected result when I try with my personal data

### ISSUE THREAD

**Issue by JunyuanDeng** [shawn615/MixNeRF#4]
I wanted to train the model on my personal data, which is similar to blender dataset.

But sometimes the rendering results are either whole white or run into nan.

Do you have any idea how to solve this problem?

Thanks in advance!!!
![image](https://github.com/shawn615/MixNeRF/assets/62542727/68f31c36-18b6-479d-a3f6-e144417d6f5c)
![image](https://github.com/shawn615/MixNeRF/assets/62542727/68985263-23da-4663-a584-ba30767f3272)

**Comment by shawn615** [comment]
There can be sometimes nan problem in our framework due to the exponential and log functions in our nll losses depending on the randomly initialized starting point.
Could you add a very small value such as 1e-10 to the denominator in line115,117 at internal/models.py and share the results?
Maybe it can reduce the nan problem.
